import { z, AssumptionIdSchema, ClaimIdSchema, EntityIdSchema, EpistemicClassSchema, EvidenceItemIdSchema, HypothesisIdSchema, JsonValueSchema, ObservationIdSchema, ReconstructionIdSchema, RendererCapabilitySchema, SourceArtifactIdSchema, WorldIdSchema, WorldRelationshipIdSchema } from "@apocrypha/domain";

const hash = z.string().regex(/^[a-fA-F0-9]{64}$/); const iso = z.string().datetime({ offset: true }); const unique = <T extends z.ZodTypeAny>(schema:T)=>z.array(schema).superRefine((v,c)=>{if(new Set(v).size!==v.length)c.addIssue({code:"custom",message:"Duplicate IDs are not permitted"});});
export const ProvenanceRefSchema=z.discriminatedUnion("type",[z.object({type:z.literal("CLAIM"),id:ClaimIdSchema}),z.object({type:z.literal("OBSERVATION"),id:ObservationIdSchema}),z.object({type:z.literal("EVIDENCE_ITEM"),id:EvidenceItemIdSchema}),z.object({type:z.literal("SOURCE_ARTIFACT"),id:SourceArtifactIdSchema}),z.object({type:z.literal("ASSUMPTION"),id:AssumptionIdSchema}),z.object({type:z.literal("UNKNOWN"),reason:z.string().min(1).optional()}),z.object({type:z.literal("GENERATIVE_FILL"),reason:z.string().min(1).optional()})]); export type ProvenanceRef=z.infer<typeof ProvenanceRefSchema>;
export const ReconstructionRelationshipSchema=z.object({relationshipId:WorldRelationshipIdSchema,subjectEntityId:EntityIdSchema,predicate:z.string().min(1),objectEntityId:EntityIdSchema,epistemicClass:EpistemicClassSchema,claimIds:unique(ClaimIdSchema),assumptionIds:unique(AssumptionIdSchema)}); export type ReconstructionRelationship=z.infer<typeof ReconstructionRelationshipSchema>;
const ReconstructionEntitySchema=z.object({entityId:EntityIdSchema,existence:z.enum(["PRESENT","ABSENT","UNRESOLVED"]),properties:z.array(z.object({property:z.string().min(1),value:JsonValueSchema,epistemicClass:EpistemicClassSchema,claimIds:unique(ClaimIdSchema),assumptionIds:unique(AssumptionIdSchema)})),rendererHints:z.object({semanticRegion:z.string().min(1).optional()}).optional()});
const RenderingPolicySchema=z.object({unknownHandling:z.enum(["KEEP_AMBIGUOUS","ALLOW_FILL"]),generatedFillLabelRequired:z.literal(true),preserveContestedElements:z.boolean(),excludedEntityIds:unique(EntityIdSchema),notes:z.array(z.string().min(1)).optional()});
export const ReconstructionSpecSchema=z.object({specVersion:z.string().min(1),reconstructionId:ReconstructionIdSchema,hypothesisId:HypothesisIdSchema,worldId:WorldIdSchema,worldRevision:z.number().int().nonnegative(),entities:z.array(ReconstructionEntitySchema),relationships:z.array(ReconstructionRelationshipSchema),sourceArtifactIds:unique(SourceArtifactIdSchema),claimIds:unique(ClaimIdSchema),assumptionIds:unique(AssumptionIdSchema),requiredCapabilities:unique(RendererCapabilitySchema),renderingPolicy:RenderingPolicySchema,provenanceIndex:z.record(z.string().min(1),z.array(ProvenanceRefSchema)),canonicalHash:hash}); export type ReconstructionSpec=z.infer<typeof ReconstructionSpecSchema>;
export const RenderManifestSchema=z.object({reconstructionId:ReconstructionIdSchema,hypothesisId:HypothesisIdSchema,worldRevision:z.number().int().nonnegative(),provider:z.string().min(1),adapter:z.string().min(1),model:z.string().min(1),providerModelVersion:z.string().min(1).optional(),requestOrJobId:z.string().min(1),promptOrRequest:JsonValueSchema,parameters:JsonValueSchema,sourceArtifactIds:unique(SourceArtifactIdSchema),claimIds:unique(ClaimIdSchema),assumptionIds:unique(AssumptionIdSchema),epistemicClasses:unique(EpistemicClassSchema),regenerationMode:z.enum(["INITIAL","FULL","PARTIAL"]),dirtyEntityIds:unique(EntityIdSchema).optional(),generatedAt:iso,outputPath:z.string().min(1),outputSha256:hash}); export type RenderManifest=z.infer<typeof RenderManifestSchema>;
